slotmachine:
  bet:
    min: 10
    max: 10000
    step: 10
  cooldown-seconds: 3
  two-match-multiplier: 0.5
  payouts:
    DIAMOND: 100
    EMERALD: 20
    GOLDEN_APPLE: 5
    APPLE: 2
    COAL: 1
  probabilities: # 퍼센트 단위 (합 100)
    DIAMOND: 0.5
    EMERALD: 2.0
    GOLDEN_APPLE: 7.5
    APPLE: 20.0
    COAL: 70.0
  animation:
    frame-interval-ticks: 2
    left-frames: 22
    middle-frames-delay: 6 # 좌 -> 중 지연 프레임
    right-frames-delay: 6  # 중 -> 우 지연 프레임
    no-consecutive-center-duplicate: true # 중앙 라인(포커스) 같은 심볼 연속 방지
    visual-probabilities: # 연출(애니메이션)용 가중치 (합 필요 없음, 비율로 처리). 고등급 많이 보이도록 기본값.
      DIAMOND: 40
      EMERALD: 25
      GOLDEN_APPLE: 15
      APPLE: 10
      COAL: 10
  jackpot:
    announce: true
    admin-log: true
    minimum-broadcast-payout: 0 # 0이면 모든 잭팟 방송
